var config={
	"title":"Fruits",
	"corrAns":[6,1,9,2,3,4,7,5,8],
	"draggable":[
		"images/apple.png",
		"images/mango.png",
		"images/orange.png",
		"images/guava.png",
		"images/pineapple.png",
		"images/papaya.png",
		"images/litchi.png",
		"images/grape.png",
		"images/coconut.png"
	],
	"droppable":[
		"Mango",
		"Guava",
		"Pineapple",
		"Papaya",
		"Grape",
		"Apple",
		"Lichi",
		"Coconut",
		"Orange"
	]
}